feat(contact): added contact page with form and mailer system
WizBhoo/API_CV_Portfolio_Symfony pull request #3
Opened 2020-08-25 12:41 UTC by WizBhoo

Hello Yann,

Could you please review this feature ?
I added the contact page with the appropriate form and i have implemented a mailer system using google-mailer.

Thanks.

2020-08-25 13:00 UTC, drixs6o9 commented on src/Mailer/MailerMessage.php
> +            ->from(new Address('wizbhoo.dev@gmail.com', 'APi - Contact Form'))
Use the real sender email no ?

2020-08-25 13:01 UTC, drixs6o9 commented on templates/emails/contactHTML.html.twig
> +</ul>
Email template must have html / body tags !

2020-08-25 13:16 UTC, WizBhoo commented on src/Mailer/MailerMessage.php
> +            ->from(new Address('wizbhoo.dev@gmail.com', 'APi - Contact Form'))
It's this one : the mail is sent from wizbhoo.dev

2020-08-25 15:19 UTC, drixs6o9 requested changes
No tests ?

2020-08-25 15:19 UTC, drixs6o9 commented on src/Mailer/Sender.php
> +    }
```suggestion
    /**
     * Send email.
     *
     * @param TemplatedEmail $email
     *
     * @return void
     *
     * @throws TransportExceptionInterface
     */
    public function sendEmail(TemplatedEmail $email): void
    {
        $this->mailer->send($email);
    }
```

2020-08-25 15:19 UTC, drixs6o9 commented on src/Manager/ContactManager.php
> +    public function buildContactEmail(array $contact): void
```suggestion
    public function sendContactEmail(array $contact): void
```

2020-08-25 15:19 UTC, drixs6o9 commented on src/Manager/ContactManager.php
> +            )
```suggestion
            ->context([
                'contact' => $contact,
            ])
```

2020-08-26 09:25 UTC, drixs6o9 approved these changes

2020-08-26 09:39 UTC, merged